In [3]:
import pandas as pd
from sqlalchemy import create_engine

DB_URL = "postgresql+psycopg2://postgres:postgres@localhost:5432/olist"

engine = create_engine(DB_URL)

print("Connection object created successfully")

Connection object created successfully

In [4]:
from sqlalchemy import inspect

inspector = inspect(engine)

tables = inspector.get_table_names()

print("Tables in database:")
for table in tables:
    print("-", table)

Tables in database:
- customers
- orders
- products
- sellers
- order_items
- order_payments
- order_reviews
- geolocation
- product_category_translation

In [5]:
dataframes = {}

for table in tables:
    df = pd.read_sql(f"SELECT * FROM {table}", engine)
    dataframes[table] = df
    
    print(f"{table}: {len(df)} rows")

customers: 99441 rows
orders: 99441 rows
products: 32951 rows
sellers: 3095 rows
order_items: 112650 rows
order_payments: 103886 rows
order_reviews: 99224 rows
geolocation: 1000163 rows
product_category_translation: 71 rows

In [6]:
for table, df in dataframes.items():
    print("=" * 60)
    print("TABLE:", table)
    print("Shape:", df.shape)
    print("Columns:")
    print(df.columns.tolist())
    print("\nFirst 2 rows:")
    display(df.head(2))

============================================================
TABLE: customers
Shape: (99441, 5)
Columns:
['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

First 2 rows:

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP

============================================================
TABLE: orders
Shape: (99441, 8)
Columns:
['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

First 2 rows:

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13

============================================================
TABLE: products
Shape: (32951, 9)
Columns:
['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

First 2 rows:

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0

============================================================
TABLE: sellers
Shape: (3095, 4)
Columns:
['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']

First 2 rows:

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP

============================================================
TABLE: order_items
Shape: (112650, 7)
Columns:
['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']

First 2 rows:

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.9,19.93

============================================================
TABLE: order_payments
Shape: (103886, 5)
Columns:
['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']

First 2 rows:

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39

============================================================
TABLE: order_reviews
Shape: (99224, 7)
Columns:
['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

First 2 rows:

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10,2018-03-11 03:05:13

============================================================
TABLE: geolocation
Shape: (1000163, 5)
Columns:
['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng', 'geolocation_city', 'geolocation_state']

First 2 rows:

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP

============================================================
TABLE: product_category_translation
Shape: (71, 2)
Columns:
['product_category_name', 'product_category_name_english']

First 2 rows:

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories

In [7]:
customers = dataframes["customers"]

print("Total rows:", len(customers))
print("Unique customer_id:", customers["customer_id"].nunique())
print("Unique customer_unique_id:", customers["customer_unique_id"].nunique())

print("Duplicate customer_id:",
      customers["customer_id"].duplicated().sum())

print("Duplicate customer_unique_id:",
      customers["customer_unique_id"].duplicated().sum())

Total rows: 99441
Unique customer_id: 99441
Unique customer_unique_id: 96096
Duplicate customer_id: 0
Duplicate customer_unique_id: 3345

In [8]:
summary = []

for table, df in dataframes.items():
    summary.append({
        "table": table,
        "rows": df.shape[0],
        "columns": df.shape[1],
        "duplicate_rows": df.duplicated().sum()
    })

summary_df = pd.DataFrame(summary)

display(summary_df)

                          table     rows  columns  duplicate_rows
0                     customers    99441        5               0
1                        orders    99441        8               0
2                      products    32951        9               0
3                       sellers     3095        4               0
4                   order_items   112650        7               0
5                order_payments   103886        5               0
6                 order_reviews    99224        7               0
7                   geolocation  1000163        5          261831
8  product_category_translation       71        2               0

In [9]:
key_checks = {
    "customers": ["customer_id", "customer_unique_id"],
    "orders": ["order_id", "customer_id"],
    "products": ["product_id"],
    "sellers": ["seller_id"],
    "order_items": ["order_id", "product_id", "seller_id"],
    "order_payments": ["order_id"],
    "order_reviews": ["review_id", "order_id"],
    "geolocation": ["geolocation_zip_code_prefix"],
    "product_category_translation": ["product_category_name"]
}

for table, columns in key_checks.items():
    df = dataframes[table]

    print("=" * 60)
    print("TABLE:", table)

    for col in columns:
        print(
            col,
            "| unique:", df[col].nunique(),
            "| duplicates:", df[col].duplicated().sum()
        )

============================================================
TABLE: customers
customer_id | unique: 99441 | duplicates: 0
customer_unique_id | unique: 96096 | duplicates: 3345
============================================================
TABLE: orders
order_id | unique: 99441 | duplicates: 0
customer_id | unique: 99441 | duplicates: 0
============================================================
TABLE: products
product_id | unique: 32951 | duplicates: 0
============================================================
TABLE: sellers
seller_id | unique: 3095 | duplicates: 0
============================================================
TABLE: order_items
order_id | unique: 98666 | duplicates: 13984
product_id | unique: 32951 | duplicates: 79699
seller_id | unique: 3095 | duplicates: 109555
============================================================
TABLE: order_payments
order_id | unique: 99440 | duplicates: 4446
============================================================
TABLE: order_reviews
review_id | unique: 98410 | duplicates: 814
order_id | unique: 98673 | duplicates: 551
============================================================
TABLE: geolocation
geolocation_zip_code_prefix | unique: 19015 | duplicates: 981148
============================================================
TABLE: product_category_translation
product_category_name | unique: 71 | duplicates: 0

In [10]:
for table in ["orders", "order_items", "order_payments"]:
    print("=" * 60)
    print("TABLE:", table)
    print(dataframes[table].columns.tolist())
    display(dataframes[table].head(3))

============================================================
TABLE: orders
['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04

============================================================
TABLE: order_items
['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.9,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.0,17.87

============================================================
TABLE: order_payments
['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71

In [11]:
display(dataframes["order_payments"].head(5))

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [12]:
payments = dataframes["order_payments"]

repeated_order = payments[
    payments["order_id"].duplicated(keep=False)
].sort_values("order_id")

display(repeated_order.head(10))

,order_id,payment_sequential,payment_type,payment_installments,payment_value
80856,0016dfedd97fc2950e388d2971d718c7,2,voucher,1,17.92
89575,0016dfedd97fc2950e388d2971d718c7,1,credit_card,5,52.63
20036,002f19a65a2ddd70a090297872e6d64e,1,voucher,1,44.11
98894,002f19a65a2ddd70a090297872e6d64e,2,voucher,1,33.18
30155,0071ee2429bc1efdc43aa3e073a5290e,2,voucher,1,92.44
10244,0071ee2429bc1efdc43aa3e073a5290e,1,voucher,1,100.00
16459,009ac365164f8e06f59d18a08045f6c4,2,voucher,1,4.50
15298,009ac365164f8e06f59d18a08045f6c4,6,voucher,1,4.17
32058,009ac365164f8e06f59d18a08045f6c4,4,voucher,1,5.45
285,009ac365164f8e06f59d18a08045f6c4,5,voucher,1,8.75

In [13]:
payments_agg = (
    payments
    .groupby("order_id")
    .agg(
        total_payment_value=("payment_value", "sum"),
        payment_records=("payment_sequential", "count"),
        max_installments=("payment_installments", "max"),
        payment_types=("payment_type", lambda x: ", ".join(sorted(set(x.dropna()))))
    )
    .reset_index()
)

display(payments_agg.head())

,order_id,total_payment_value,payment_records,max_installments,payment_types
0,00010242fe8c5a6d1ba2dd792cb16214,72.19,1,2,credit_card
1,00018f77f2f0320c557190d7a144bdd3,259.83,1,3,credit_card
2,000229ec398224ef6ca0657da4fc703e,216.87,1,5,credit_card
3,00024acbcdf0a6daa1e931b038114c75,25.78,1,2,credit_card
4,00042b26cf59d7ce69dfabb4e55b4fd9,218.04,1,3,credit_card

In [14]:
print("Rows before aggregation:", len(payments))
print("Rows after aggregation:", len(payments_agg))
print("Unique order_id after aggregation:", payments_agg["order_id"].nunique())
print("Duplicate order_id after aggregation:", payments_agg["order_id"].duplicated().sum())

Rows before aggregation: 103886
Rows after aggregation: 99440
Unique order_id after aggregation: 99440
Duplicate order_id after aggregation: 0

In [15]:
items = dataframes["order_items"]

print(items.columns.tolist())
display(items.head(5))

['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [16]:
items_agg = (
    items
    .groupby("order_id")
    .agg(
        item_count=("order_item_id", "count"),
        total_item_price=("price", "sum"),
        total_freight_value=("freight_value", "sum"),
        unique_products=("product_id", "nunique"),
        unique_sellers=("seller_id", "nunique")
    )
    .reset_index()
)

display(items_agg.head())

,order_id,item_count,total_item_price,total_freight_value,unique_products,unique_sellers
0,00010242fe8c5a6d1ba2dd792cb16214,1,58.90,13.29,1,1
1,00018f77f2f0320c557190d7a144bdd3,1,239.90,19.93,1,1
2,000229ec398224ef6ca0657da4fc703e,1,199.00,17.87,1,1
3,00024acbcdf0a6daa1e931b038114c75,1,12.99,12.79,1,1
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,199.90,18.14,1,1

In [17]:
orders = dataframes["orders"]

print(orders.columns.tolist())
display(orders.head())

['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26

In [18]:
customers = dataframes["customers"]

ml_table = orders.merge(
    customers,
    on="customer_id",
    how="left"
)

print("Rows after customers join:", len(ml_table))
print("Unique order_id:", ml_table["order_id"].nunique())
print("Duplicate order_id:", ml_table["order_id"].duplicated().sum())

display(ml_table.head())

Rows after customers join: 99441
Unique order_id: 99441
Duplicate order_id: 0

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,barreiras,BA
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP

In [19]:
ml_table = ml_table.merge(
    items_agg,
    on="order_id",
    how="left"
)

print("Rows after items join:", len(ml_table))
print("Unique order_id:", ml_table["order_id"].nunique())
print("Duplicate order_id:", ml_table["order_id"].duplicated().sum())

Rows after items join: 99441
Unique order_id: 99441
Duplicate order_id: 0

In [20]:
ml_table = ml_table.merge(
    payments_agg,
    on="order_id",
    how="left"
)

print("Rows after payments join:", len(ml_table))
print("Unique order_id:", ml_table["order_id"].nunique())
print("Duplicate order_id:", ml_table["order_id"].duplicated().sum())

Rows after payments join: 99441
Unique order_id: 99441
Duplicate order_id: 0

In [21]:
print("Missing item_count:", ml_table["item_count"].isna().sum())
print("Missing total_item_price:", ml_table["total_item_price"].isna().sum())
print("Missing total_payment_value:", ml_table["total_payment_value"].isna().sum())
print("Missing payment_records:", ml_table["payment_records"].isna().sum())

Missing item_count: 775
Missing total_item_price: 775
Missing total_payment_value: 1
Missing payment_records: 1

In [22]:
missing_items = ml_table[ml_table["item_count"].isna()]

print(missing_items["order_status"].value_counts())

order_status
unavailable    603
canceled       164
created          5
invoiced         2
shipped          1
Name: count, dtype: int64

In [23]:
missing_payments = ml_table[ml_table["total_payment_value"].isna()]

print(missing_payments["order_status"].value_counts())

order_status
delivered    1
Name: count, dtype: int64

In [24]:
print("Final ML table shape:", ml_table.shape)
print("Unique order_id:", ml_table["order_id"].nunique())
print("Duplicate order_id:", ml_table["order_id"].duplicated().sum())

display(ml_table.head())

Final ML table shape: (99441, 21)
Unique order_id: 99441
Duplicate order_id: 0

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,customer_state,item_count,total_item_price,total_freight_value,unique_products,unique_sellers,total_payment_value,payment_records,max_installments,payment_types
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,SP,1.0,29.99,8.72,1.0,1.0,38.71,3.0,1.0,"credit_card, voucher"
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,...,BA,1.0,118.70,22.76,1.0,1.0,141.46,1.0,1.0,boleto
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,GO,1.0,159.90,19.22,1.0,1.0,179.12,1.0,3.0,credit_card
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,7c142cf63193a1473d2e66489a9ae977,59296,...,RN,1.0,45.00,27.20,1.0,1.0,72.20,1.0,1.0,credit_card
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6,9195,...,SP,1.0,19.90,8.72,1.0,1.0,28.62,1.0,1.0,credit_card

In [27]:
print("""
Notebook 01 Summary
-------------------
- Loaded 9 Olist database tables.
- Checked row counts, candidate keys, and duplicate rows.
- orders contains one row per order.
- order_items and order_payments contain multiple rows per order.
- Aggregated order_items and order_payments before joining.
- Built final ML table with one row per order.
- Final table contains no duplicate order_id values.
""")

Notebook 01 Summary
-------------------
- Loaded 9 Olist database tables.
- Checked row counts, candidate keys, and duplicate rows.
- orders contains one row per order.
- order_items and order_payments contain multiple rows per order.
- Aggregated order_items and order_payments before joining.
- Built final ML table with one row per order.
- Final table contains no duplicate order_id values.

In [25]:
from pathlib import Path

ARTIFACTS_DIR = Path("../artifacts")
ARTIFACTS_DIR.mkdir(exist_ok=True)

In [26]:
output_path = ARTIFACTS_DIR / "ml_table.csv"

ml_table.to_csv(output_path, index=False)

print("Saved to:", output_path)

Saved to: ..\artifacts\ml_table.csv